orchestrator:
  build: .
  environment:
   - PAZ_ORCHESTRATOR_SVCDIR_URL=http://svcdir_1:9001
   - PAZ_ORCHESTRATOR_PORT=9000
   - PAZ_ORCHESTRATOR_SCHEDULER_URL=http://scheduler_1:9002
   - PAZ_ORCHESTRATOR_ETCD_ENDPOINT=etcd_1:2379
   - PAZ_ORCHESTRATOR_CORS=true
   - PAZ_ORCHESTRATOR_DNS_DISABLED=true
   - DEBUG
  links:
   - svcdir
   - etcd
   - scheduler
  ports:
   - "9000:9000"
   - "1337:1337"
svcdir:
  image: quay.io/yldio/paz-service-directory
  environment:
   - PAZ_SERVICE_DIRECTORY_PORT=9001
  ports:
   - "9001:9001"
etcd:
  extends:
    file: docker-compose-local.yml
    service: etcd
  image: quay.io/coreos/etcd:latest
  ports:
   - "2379:2379"
   - "2380:2380"
scheduler:
  image: quay.io/yldio/paz-scheduler
  environment:
   - PAZ_SCHEDULER_SVCDIR_URL=svcdir_1:9001
   - PAZ_SCHEDULER_PORT=9002
   - PAZ_SCHEDULER_GEN_KEY=false
   - PAZ_SCHEDULER_NODEPLOY=true
   - PAZ_SCHEDULER_ETCD_ENDPOINT=etcd_1:2379
   - DEBUG
  links:
   - svcdir
   - etcd
  ports:
    - "9002:9002"

